import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Future of Health Africa, 2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://scripts.sirv.com/sirvjs/v3/sirv.js"
          async
          defer
        ></script>
      </head>
      <body className={`antialiased font-euclid`}>
        {children}
        <Toaster
          position="top-right"
          reverseOrder={false}
          gutter={8}
          toastOptions={{
            duration: 4000,
            style: {
              background: "#fff",
              color: "#070031",
              fontSize: "16px",
              fontFamily: "'Euclid Circular B', sans-serif",
              padding: "16px",
              borderRadius: "8px",
              boxShadow:
                "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
            },
            success: {
              duration: 4000,
              iconTheme: {
                primary: "#114287",
                secondary: "#fff",
              },
              style: {
                border: "1px solid #114287",
              },
            },
            error: {
              duration: 5000,
              iconTheme: {
                primary: "#ef4444",
                secondary: "#fff",
              },
              style: {
                border: "1px solid #ef4444",
              },
            },
            loading: {
              iconTheme: {
                primary: "#114287",
                secondary: "#fff",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
